### PR TITLE
add labels to data

### PR DESCRIPTION
**Pull request by ElijahWandimi**

### CODE REVIEW

**Review by VictorOmondi1997 — CHANGES_REQUESTED** [review]
This looks great @ElijahWandimi 
There are some Pylint errors, please fix them. This should be related to the version of libraries, and I believe some other issues will come up in relation to your Python code.
```sh
ERROR: Ignored the following versions that require a different python version: 1.11.0 Requires-Python <3.13,>=3.9; 1.11.0rc1 Requires-Python <3.13,>=3.9; 1.11.0rc2 Requires-Python <3.13,>=3.9; 1.11.1 Requires-Python <3.13,>=3.9; 1.11.2 Requires-Python <3.13,>=3.9; 1.25.0 Requires-Python >=3.9; 1.25.0rc1 Requires-Python >=3.9; 1.25.1 Requires-Python >=3.9; 1.25.2 Requires-Python >=3.9; 1.26.0b1 Requires-Python <3.13,>=3.9; 2.1.0rc0 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement scipy==1.11.2 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.8.0rc1, 1.8.0rc2, 1.8.0rc3, 1.8.0rc4, 1.8.0, 1.8.1, 1.9.0rc1, 1.9.0rc2, 1.9.0rc3, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0rc1, 1.10.0rc2, 1.10.0, 1.10.1)
ERROR: No matching distribution found for scipy==1.11.2
```

**Comment by ElijahWandimi** [comment]
I've downgraded the scipy version to accomodate for python 3.8

**Comment by VictorOmondi1997** [comment]
This is ready to go, We can **merge** as is but if you have the bandwidth to work on the following  4 pylint failures, I'll break it down for you:
* `data_processing/add_labels.py:5:0: E0401: Unable to import 'datasets' (import-error)`: To fix this you can add `datasets` library in the `requirements.txt` if this library is in your environment would you rerun `python -m pip freeze > requrements.txt`?
* Python Lints:
  * Doc strings issues: Provide docstrings for all the functions and class
    * `data_processing/add_labels.py:10:0: C0116: Missing function or method docstring (missing-function-docstring)`
    * `data_processing/add_labels.py:14:0: C0115: Missing class docstring (missing-class-docstring)`
    * `data_processing/add_labels.py:24:0: C0116: Missing function or method docstring (missing-function-docstring)`
  * Add 2 methods in your class, for lint to pass there must be at least 2 methods in a class
    * `data_processing/add_labels.py:14:0: R0[9](https://github.com/TechBlurbs/maandamano-mondays-sentiment-analysis/actions/runs/5990969973/job/16248853125?pr=18#step:5:10)03: Too few public methods (0/2) (too-few-public-methods)`
 * Provide a clearer variable name: `df` could be renamed `data` maybe (or `data_frame`):
    * `data_processing/add_labels.py:25:4: C0[10](https://github.com/TechBlurbs/maandamano-mondays-sentiment-analysis/actions/runs/5990969973/job/16248853125?pr=18#step:5:11)3: Variable name "df" doesn't conform to snake_case naming style (invalid-name)`

**Comment by ElijahWandimi** [comment]
Sure, I can work on some of those:

- I'll add the docstrings and rename the dataframe to comply with pylint. 
- The class however, is a configuration class, I'll let it stay as is.

Thanks for the breakdown.

**Review by VictorOmondi1997 — APPROVED** [review]
Looks great. Feel free to `Rebase and Merge`.

**Comment by VictorOmondi1997** [comment]
@ElijahWandimi I'd like to share the following resources that might help you improve your Git skills
1. [How to write a commit message](https://cbea.ms/git-commit/)
2. [Squashing commits](https://www.freecodecamp.org/news/git-squash-commits/): This is so important especially when you have smaller commits that you'd like to merge as 1 commit. For example, in this PR the last two commits that are the same, f7d27b6 and 6d6a07e, they can be squashed into 1 commit.

**Comment by ElijahWandimi** [comment]
@VictorOmondi1997  Thanks for the resources.
I appreciate.

**Pull request merged**
